Vagrant.configure("2") do |config|
  BOX_NAME = "bento/ubuntu-22.04"
  
  config.vm.define "berkayS" do |server|
    server.vm.box = BOX_NAME
    server.vm.hostname = "berkayS"
    server.vm.network "private_network", ip: "192.168.56.110"
    
    server.vm.provider "parallels" do |prl|
      prl.memory = 1024
      prl.cpus = 1
    end
    
    # Makine ayağa kalkarken çalışacak script
    server.vm.provision "shell", inline: <<-SHELL
      bash /vagrant/scripts/server.sh
    SHELL
  end
end
